/* Generated by AN DISI Unibo */ 
package it.unibo.ctx_mapperqak22
import it.unibo.kactor.QakContext
import it.unibo.kactor.sysUtil
import kotlinx.coroutines.runBlocking

fun main() = runBlocking {
	QakContext.createContexts(
	        "localhost", this, "mapperqak22_system.pl", "sysRules.pl"
	)
}

